baseURL = 'https://gabe.cafe/'
languageCode = 'en-us'
title = "Gabe's Media Cafe"
theme = 'smol'

[outputs]
  home = ['html', 'rss']


# Parameters
[params]
    subtitle = "Musings on what I am watching, listening to, or things that I have collected"
    date_format = "02 Jan 2006"


# Header
[menu]
  [[menu.main]]
        identifier = "posts"
        name = "Posts"
        url = "/posts/"
        weight = 1

  [[menu.main]]
        identifier = "categories"
        name = "Categories"
        url = "/categories/"
        weight = 2

  [[menu.main]]
        identifier = "tags"
        name = "Tags"
        url = "/tags/"
        weight = 3

  [[menu.main]]
        identifier = "About"
        name = "About"
        url = "/about/"
        weight = 4
# Footer
  [[menu.footer]]
        name = "Github"
        url = "https://github.com/example"
        weight = 1

    [[menu.footer]]
        name = "Mastodon"
        url = "https://example.com/@user"
        weight = 2

    [[menu.footer]]
        name = "Imprint"
        url = "/imprint"
        weight = 3

[security]
  enableInlineShortcodes = true


